'''
Problem 2: Even Fibonacci numbers
    Each new term in the Fibonacci sequence is generated by adding the previous
    two terms. By starting with 1 and 2, the first 10 terms will be:
        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    By considering the terms in the Fibonacci sequence whose values do not 
    exceed four million, find the sum of the even-valued terms.
'''
def answer():
    '''
    Find and return the sum of all the even fibonacci numbers that do not 
    exceed four million
    '''
    sum_even = 0
    previous_term, this_term = 1, 2
    while this_term <= 4000000:
        if this_term % 2 == 0:
            sum_even += this_term
        next_term = previous_term + this_term
        previous_term, this_term = this_term, next_term
    return sum_even

if __name__ == '__main__':
    print answer() # 4613732
    
        